let form = document.getElementById('stud');

const heading = document.createElement('h1');
heading.textContent = "STUDENT DETAILS FORM";
heading.style.textAlign = "center";
form.appendChild(heading);

let nameLabel = document.createElement('label');
nameLabel.textContent = "NAME:";
form.appendChild(nameLabel);
let nameInput = document.createElement('input');
nameInput.type = "text";
nameInput.name = "name";
nameInput.required = true;
form.appendChild(nameInput);
form.appendChild(document.createElement('br'));
form.appendChild(document.createElement('br'));

let rollnoLabel = document.createElement("label");
rollnoLabel.textContent = "ROLL NO:";
form.appendChild(rollnoLabel);
let rollnoInput = document.createElement("input");
rollnoInput.type = "number";
rollnoInput.name = "rollno";
rollnoInput.required = true;
form.appendChild(rollnoInput);
form.appendChild(document.createElement('br'));
form.appendChild(document.createElement('br'));

let emailLabel = document.createElement("label");
emailLabel.textContent = "EMAIL:";
form.appendChild(emailLabel);
let emailInput = document.createElement("input");
emailInput.type = "email";
emailInput.name = "email";
emailInput.required = true;
form.appendChild(emailInput);
form.appendChild(document.createElement('br'));
form.appendChild(document.createElement('br'));

let phoneLabel = document.createElement("label");
phoneLabel.textContent = "PHONE NUMBER:";
form.appendChild(phoneLabel);
let phoneInput = document.createElement("input");
phoneInput.type = "number";
phoneInput.name = "phone";
phoneInput.required = true;
form.appendChild(phoneInput);
form.appendChild(document.createElement('br'));
form.appendChild(document.createElement('br'));

let dobLabel = document.createElement("label");
dobLabel.textContent = "DATE OF BIRTH:";
form.appendChild(dobLabel);
let dobInput = document.createElement("input");
dobInput.type = "date";
dobInput.name = "dob";
dobInput.required = true;
form.appendChild(dobInput);
form.appendChild(document.createElement('br'));
form.appendChild(document.createElement('br'));

let genderLabel = document.createElement("label");
genderLabel.textContent = "GENDER:";
form.appendChild(genderLabel);
let genderInput = document.createElement("select");
genderInput.name = "gender";
let optionSelect = document.createElement("option");
optionSelect.value = "Select Option";
optionSelect.text = "Select Option";
genderInput.appendChild(optionSelect);
let optionMale = document.createElement("option");
optionMale.value = "Male";
optionMale.text = "Male";
genderInput.appendChild(optionMale);
let optionFemale = document.createElement("option");
optionFemale.value = "Female";
optionFemale.text = "Female";
genderInput.appendChild(optionFemale);
let optionOther = document.createElement("option");
optionOther.value = "Other";
optionOther.text = "Other";
genderInput.appendChild(optionOther);
genderInput.required = true;
form.appendChild(genderInput);
form.appendChild(document.createElement('br'));
form.appendChild(document.createElement('br'));

let addressLabel = document.createElement("label");
addressLabel.textContent = "ADDRESS:";
form.appendChild(addressLabel);
let addressInput = document.createElement("textarea");
addressInput.name = "address";
addressInput.required = true;
form.appendChild(addressInput);
form.appendChild(document.createElement('br'));
form.appendChild(document.createElement('br'));

let courseLabel = document.createElement("label");
courseLabel.textContent = "COURSE:";
form.appendChild(courseLabel);
let courseInput = document.createElement("select");
courseInput.name = "course";
let option1 = document.createElement("option");
option1.value = "Select Option";
option1.text = "Select Option";
courseInput.appendChild(option1);
let option2 = document.createElement("option");
option2.value = "BA";
option2.text = "BA";
courseInput.appendChild(option2);
let option3 = document.createElement("option");
option3.value = "BCom";
option3.text = "BCom";
courseInput.appendChild(option3);
let option4 = document.createElement("option");
option4.value = "BTech";
option4.text = "BTech";
courseInput.appendChild(option4);
let option5 = document.createElement("option");
option5.value = "MTech";
option5.text = "MTech";
courseInput.appendChild(option5);
form.appendChild(courseInput);
form.appendChild(document.createElement('br'));
form.appendChild(document.createElement('br'));

let submitButton = document.createElement("button");
submitButton.type = "submit";
submitButton.textContent = "SUBMIT";
form.appendChild(submitButton);
alert("SUBMITTED SUCCESSFULLY!!");